FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential cmake ninja-build git git-lfs ca-certificates \
      pkg-config python3 python3-pip \
      doxygen yasm nasm perl \
      wget curl file fuse libfuse2 desktop-file-utils \
      libssl-dev libxml2-dev libsqlite3-dev libsoup2.4-dev \
      libopus-dev libvpx-dev libbz2-dev \
      libavcodec-dev libavformat-dev libavutil-dev libswscale-dev \
      libx11-dev libxv-dev libxrandr-dev libxfixes-dev \
      libpulse-dev libasound2-dev libv4l-dev libudev-dev \
      qtbase5-dev qtdeclarative5-dev \
      qtquickcontrols2-5-dev \
      qtmultimedia5-dev qttools5-dev qttools5-dev-tools \
      libqt5svg5-dev \
      qml-module-qtquick-controls2 qml-module-qtquick-dialogs \
      qml-module-qt-labs-platform \
      qt5-image-formats-plugins \
      libdbus-1-dev \
      libglew-dev libxinerama-dev libgles2-mesa-dev \
      zlib1g-dev libjpeg-dev libpng-dev \
      libglib2.0-dev libevent-dev libresolv-wrapper \
      meson && \
    python3 -m pip install --quiet pystache six && \
    rm -rf /var/lib/apt/lists/*
