set(APPLICATION_DESCRIPTION "Lunyso — RSSI à temps partagé")
set(APPLICATION_ID "com.lunyso.lunyso")
set(APPLICATION_NAME Lunyso)
set(APPLICATION_URL "https://lunyso.com")
set(APPLICATION_VENDOR "Lunyso")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2010")

set(EXECUTABLE_NAME lunyso)
